-- Este archivo ha sido desactivado y vaciado para evitar colisiones con el sistema de Database Webhooks visuales oficiales de Supabase.
-- Puedes configurar de forma visual tu Webhook HTTP en Supabase (Database -> Webhooks) con los siguientes datos:
-- URL: https://whisper-eight-pied.vercel.app/api/avatars/notify-pending
-- Cabecera 1: Content-Type: application/json
-- Cabecera 2: Authorization: Bearer d7c92b51-7f91-49b0-8e12-4019bfb823e4
